# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-24 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popeye', '0002_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Balance',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
