# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-25 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popeye', '0003_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentwriting',
            name='is_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='websitebuilding',
            name='is_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='websitebuilding',
            name='is_paid',
            field=models.IntegerField(default=0),
        ),
    ]
