# Generated by Django 2.0 on 2017-12-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popeye', '0005_websitebuilding_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitebuilding',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
