# Generated by Django 2.0 on 2017-12-30 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popeye', '0006_auto_20171230_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitebuilding',
            name='title',
        ),
    ]
