# Generated by Django 2.0 on 2017-12-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popeye', '0008_websitebuilding_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonContentWriting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('word_count', models.IntegerField()),
                ('article_cost', models.CharField(max_length=20)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('is_done', models.IntegerField(default=0)),
                ('is_paid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AnonWebsiteBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('company', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('navigation_contents', models.CharField(max_length=500)),
                ('website_cost', models.CharField(max_length=20)),
                ('additional_instructions', models.CharField(max_length=1000)),
                ('is_done', models.IntegerField(default=0)),
                ('is_paid', models.IntegerField(default=0)),
            ],
        ),
    ]
